CREATE ROLE repuser WITH LOGIN REPLICATION PASSWORD 'rep_pass';
GRANT CONNECT ON DATABASE travel_planner_prod TO repuser;
GRANT USAGE ON SCHEMA public TO repuser;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO repuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO repuser;